name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  url_launcher: ^6.2.5
  google_fonts: ^6.1.0
  lottie: ^3.3.1
  provider: ^6.1.5
  percent_indicator: ^4.2.0
  package_info_plus: ^8.3.0
  animate_do: ^4.2.0
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.15.1  
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.9
  uuid: ^4.0.0
  youtube_player_flutter: ^9.0.4
  flutter_inappwebview: ^6.0.0-beta.22
  intl: ^0.20.2
  permission_handler: ^12.0.1
  cached_network_image: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon3.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo3.png
    - assets/images/complete.png
    - assets/images/login.png
    - assets/success.json
    - assets/forgot.json 
    - assets/signup.json
    - assets/fire.json
    - assets/idea.json
    - assets/images/flutter_course.png
    - assets/images/network.png
    - assets/images/internet.png
    - assets/images/icon.png
    - assets/images/icon3.png
    - assets/images/learn1.json
    - assets/images/learn2.json
    - assets/login.json
    - assets/message_sent.json
    - .env
    - assets/lottie_fire.json
    - assets/images/computing1.jpg
