const List<Map<String, dynamic>> courses = [
  {
    "title": "Introduction to Cybersecurity",
    "description":
        "Learn the basics of cybersecurity, including threats, vulnerabilities, and defense strategies to protect digital assets.",
    "videoUrl": "https://www.youtube.com/watch?v=1GJ2iQ77xUQ",
    "progress": 0.4,
    "image": "course_cybersecurity.png",
    "category": "Cybersecurity",
    "instructor": "Dr. Cyber Smith",
    "duration": "8h",
    "passingThreshold": 0.7,
    "quizQuestions": [],
  },
  {
    "title": "Passwords & Authentication",
    "description":
        "Master creating strong passwords and implementing two-factor authentication to secure your accounts.",
    "videoUrl": "https://youtu.be/bfmFfD2RIcg?si=uDAejPlo4rwNo1OE",
    "progress": 0.75,
    "image": "course_passwords.png",
    "category": "Cybersecurity",
    "instructor": "Jane Secure",
    "duration": "6h",
    "passingThreshold": 0.7,
    "quizQuestions": [],
  },
  {
    "title": "Phishing & Social Engineering",
    "description":
        "Identify and defend against phishing attacks and social engineering tactics used by cybercriminals.",
    "videoUrl": "https://www.youtube.com/watch?v=8mPzRdK2oW4",
    "progress": 0.2,
    "image": "course_phishing.png",
    "category": "Cybersecurity",
    "instructor": "Alex Defender",
    "duration": "5h",
    "passingThreshold": 0.7,
    "quizQuestions": [],
  },
  {
    "title": "Network Security Basics",
    "description":
        "Explore firewalls, VPNs, and secure network configurations to safeguard data transmission.",
    "videoUrl": "https://www.youtube.com/watch?v=3QhU9jd03a0",
    "progress": 0.1,
    "image": "course_network.png",
    "category": "Networking",
    "instructor": "Network Guru",
    "duration": "6h",
    "passingThreshold": 0.7,
    "quizQuestions": [],
  },
  {
    "title": "Malware & Ransomware",
    "description":
        "Understand malware types, ransomware threats, and defensive measures to protect your systems.",
    "videoUrl": "https://www.youtube.com/watch?v=GVyU-8W7k-4",
    "progress": 0.0,
    "image": "course_malware.png",
    "category": "Cybersecurity",
    "instructor": "Malware Expert",
    "duration": "7h",
    "passingThreshold": 0.7,
    "quizQuestions": [],
  },
  {
    "title": "Social Media Safety",
    "description":
        "Learn to protect your identity and personal data while using social media platforms securely.",
    "videoUrl": "https://www.youtube.com/watch?v=fjDwwJ9dW98",
    "progress": 0.5,
    "image": "assets/images/computing1.jpg",
    "category": "Cybersecurity",
    "instructor": "Social Media Pro",
    "duration": "4h",
    "passingThreshold": 0.7,
    "quizQuestions": [],
  },
];
