// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPZLqZt3YvL0LzTwfe70GGtVgtfK9D1o',
    appId: '1:620100774107:web:ed31fb6da4517951acc4fe',
    messagingSenderId: '620100774107',
    projectId: 'shieldup-ffb307',
    authDomain: 'shieldup-ffb307.firebaseapp.com',
    storageBucket: 'shieldup-ffb307.firebasestorage.app',
    measurementId: 'G-N36YTT2458',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ79r6A_bzXsLb6aDcnaW5pOkXoZ_xEIg',
    appId: '1:620100774107:android:3acfe141d337bf85acc4fe',
    messagingSenderId: '620100774107',
    projectId: 'shieldup-ffb307',
    storageBucket: 'shieldup-ffb307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD50eTZE6dC-tQbXeDXpQ60LKA1rB96KTs',
    appId: '1:620100774107:ios:ede9cea87d192cacacc4fe',
    messagingSenderId: '620100774107',
    projectId: 'shieldup-ffb307',
    storageBucket: 'shieldup-ffb307.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD50eTZE6dC-tQbXeDXpQ60LKA1rB96KTs',
    appId: '1:620100774107:ios:ede9cea87d192cacacc4fe',
    messagingSenderId: '620100774107',
    projectId: 'shieldup-ffb307',
    storageBucket: 'shieldup-ffb307.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHPZLqZt3YvL0LzTwfe70GGtVgtfK9D1o',
    appId: '1:620100774107:web:19ec723865fa3687acc4fe',
    messagingSenderId: '620100774107',
    projectId: 'shieldup-ffb307',
    authDomain: 'shieldup-ffb307.firebaseapp.com',
    storageBucket: 'shieldup-ffb307.firebasestorage.app',
    measurementId: 'G-CYFB95TMJK',
  );
}
